name: taxi-zone
services:
  dispatch-service:
    user: root
    build:
      context: ./
      dockerfile: Dockerfile.dispatcher
    ports:
      - "8000:8000"
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  worker-service:
    build:
      context: ./
      dockerfile: Dockerfile.worker
    depends_on:
      - dispatch-service
    command: python3 main.py
    deploy:
      replicas: 5

volumes:
  dispatch-data: {}