name: taxi-zone
services:
  dispatch-service:
    user: root
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.dispatcher
    ports:
      - "8000:8000"
    command: bash -c "
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dispatch-service:/taxi/app
      - ./alembic:/taxi/alembic
    depends_on:
      - db


  worker-service:
    build:
      context: ./
      dockerfile: Dockerfile.worker
    depends_on:
      - dispatch-service
    command: python3 main.py
    deploy:
      replicas: 20

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - taxi_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD?Variable not set}
      - POSTGRES_USER=${POSTGRES_USER?Variable not set}
      - POSTGRES_DB=${POSTGRES_DB?Variable not set}
    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  dispatch-data: {}
  taxi_data: {}