"""

Revision ID: 093c0fc36a7c
Revises: 
Create Date: 2025-05-15 17:38:02.056840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '093c0fc36a7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxis',
    sa.Column('taxi_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('taxi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taxis')
    # ### end Alembic commands ###
