"""

Revision ID: 9609a7f88ff3
Revises: 3ad9ac8f8b69
Create Date: 2025-05-16 12:01:17.608699

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9609a7f88ff3"
down_revision = "3ad9ac8f8b69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trips",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trips",
        "id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
