"""

Revision ID: 3ad9ac8f8b69
Revises: 093c0fc36a7c
Create Date: 2025-05-16 10:30:48.011088

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3ad9ac8f8b69"
down_revision = "093c0fc36a7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "trips",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("taxi_id", sa.String(), nullable=True),
        sa.Column("start_x", sa.Integer(), nullable=False),
        sa.Column("start_y", sa.Integer(), nullable=False),
        sa.Column("end_x", sa.Integer(), nullable=False),
        sa.Column("end_y", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["taxi_id"],
            ["taxis.taxi_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trips")
    # ### end Alembic commands ###
